name: AUR Synchronization

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    aur-sync:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.2
            - uses: ./
              with:
                  pkg_name: blaadpapers
                  ssh_key: ${{ secrets.SSH_KEY_AUR }}
